import js from '@eslint/js'
import pluginVue from 'eslint-plugin-vue'
import tseslint from 'typescript-eslint'
import prettier from 'eslint-config-prettier'

// __KIT_VERSION__ is injected by vite.config.ts `define` from package.json, so it exists at
// runtime but not to eslint's scope analysis.
const buildTimeGlobals = { __KIT_VERSION__: 'readonly' }

export default tseslint.config(
  {
    /* src/**\/*.d.ts are GENERATED by `npm run types` (vue-tsc --emitDeclarationOnly) and
     * committed, because consumers install from a git tag and there is no publish step to build
     * them. They are artifacts, not hand-written code, and must not be linted: vue-tsc emits
     * `DefineComponent<{}, {}, …>`, which trips no-empty-object-type 82 times, and the only way
     * to "fix" that would be editing a file the next `npm run types` overwrites.
     *
     * This had been failing `npm run lint` silently ever since declarations were first
     * committed -- lint is not one of the CI steps, so nothing ever surfaced it. */
    ignores: ['dist', 'node_modules', 'src/**/*.d.ts'],
  },
  { languageOptions: { globals: buildTimeGlobals } },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...pluginVue.configs['flat/recommended'],
  prettier,
  {
    files: ['**/*.vue'],
    languageOptions: { parserOptions: { parser: tseslint.parser } },
  },
  {
    /* Build/CI scripts run under Node, not in the browser -- without this, `process` reads as an
     * undefined global. Scoped to scripts/ so the kit's own source stays browser-only, which is
     * the constraint that keeps it framework- and platform-free. */
    files: ['scripts/**/*.mjs'],
    languageOptions: { globals: { process: 'readonly', console: 'readonly' } },
  },
  {
    rules: {
      // kit is framework-free core + thin wrappers; keep it lean
      '@typescript-eslint/no-explicit-any': 'off',
      'vue/multi-word-component-names': 'off',
      'vue/no-v-html': 'off',
    },
  },
)
